ChinookApp/WebApp/Pages/AlbumQuery.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using ChinookSystem.BLL;
using ChinookSystem.Models;
#endregion

namespace WebApp.Pages
{
    public class AlbumQueryModel : PageModel
    {
        private readonly AlbumServices _services;

        [BindProperty]
        public AlbumItem Album { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? albumid { get; set; }

        [TempData]
        public string FeedBackMessage { get; set; }

        public AlbumQueryModel (AlbumServices services)
        {
            _services = services;
        }
        public void OnGet()
        {
            if (albumid.HasValue)
            {
                Album = _services.Albums_GetAlbumById((int)albumid);
            }
        }

        public IActionResult OnPost()
        {
            if (!albumid.HasValue)
            {
                FeedBackMessage = "You did not supply an album id";
            }
            return RedirectToPage(new { albumid = albumid });
        }
    }
}

ChinookApp/WebApp/Pages/ArtistQuery.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class ArtistQueryModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ChinookApp/WebApp/Pages/BasicDataMovement.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class BasicDataMovementModel : PageModel
    {
        //data field
        public string MyName;

        //properties
        [TempData]
        public string FeedBackMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? theInput { get; set; }

        //constructors

        //Behaviours (aka methods, events)
        public void OnGet()
        {
            //execute in response to a Get request from the user (browser)
            //when the page is first accessed, it issues a Get Request
            //when the page is refreshed, WITHOUT a Post, it issues a Get Request
            //when the page is retrieved in response to a form POST, the Get Request is NOT automatically requested.
            Random rnd = new Random();
            int oddeven = rnd.Next(0, 25);

            if (oddeven % 2 == 0)
            {
                MyName = $"Don is {oddeven}";
            }
            else
            {
                MyName = null;
            }
        }

        public IActionResult OnPost()
        {
            //IF you do NOT use asp-page-handler on your buttons in your form, the general method=post will request the OnPost() event
            Thread.Sleep(2000);
            string buttonValue = Request.Form["theButton"];
            FeedBackMessage = buttonValue;

            //theIActionResult of RedirectToPage() sends an OnGet request to be executed after the OnPost is complete
            //without an href, the RedirectToPage defaults to the cuurent page
            return RedirectToPage();
        }

        public IActionResult OnPostAButton()
        {
            //if you are using the asp-page-handler(xxxx) then your post events will have a method name of OnPostxxxx()
            Thread.Sleep(1000);
            FeedBackMessage = $"You pressed the handler for the A Button with an input value of {theInput}";
            return RedirectToPage(new { theInput = theInput });
        }

        public IActionResult OnPostBButton()
        {
            Thread.Sleep(1000);
            FeedBackMessage = $"You pressed the handler for the B Button with an input value of {theInput}";
            //create an anonymous object and initialize using the object initialize a property with the value you wish to retain.
            //there is NO class name, thus an anonymous object
            return RedirectToPage(new { theInput = theInput });
        }
    }
}

ChinookApp/WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ChinookApp/WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

#region Additional Namespaces
using ChinookSystem.BLL;
using ChinookSystem.Models;
#endregion


namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly AboutServices _services;

        public DatabaseVersion DbVersion { get; set; }
        //on the constructor of your Model class, injecture any service you require for this page
        //the default service injection is the ILogger class
        //we need to have access to the services (methods) in the AboutServices BLL class
        public IndexModel(ILogger<IndexModel> logger, AboutServices services)
        {
            _logger = logger;
            _services = services;
        }

        public void OnGet()
        {
            DbVersion = _services.GetDataVersion();
        }
    }
}

ChinookApp/WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ChinookApp/WebApp/Pages/AlbumQuery.cshtml
@page "{albumid?}"
@model WebApp.Pages.AlbumQueryModel
@{
}
<h1>Album Query</h1>

<form method="post">
    <label>
        Entry an album id: <input type="number" asp-for="albumid" />
    </label>
    <button type="submit">Search</button>

    <p style="color: firebrick; font-weight: bold;">@Model.FeedBackMessage</p>

    @if (Model.albumid.HasValue)
    {
        if (Model.Album == null)
        {
            <p>The album id entered does not exist.</p>
        }
        else
        {
            <p>Album ID: @Model.Album.AlbumId</p>
            <p>Title: @Model.Album.Title</p>
            <p>Artist ID: @Model.Album.ArtistId</p>
            <p>Year: @Model.Album.ReleaseYear</p>
            <p>Label: @Model.Album.ReleaseLabel</p>

        }
    }
    else
    {
        <p>To display an album you need to enter the album id.</p>
    }
</form>

ChinookApp/WebApp/Pages/ArtistQuery.cshtml
@page
@model WebApp.Pages.ArtistQueryModel
@{
}
@* if you needed validation on your page you can add *@
@section scripts {
    <partial name="_ValidationScriptsPartial"? />
}
<h1>Artist Query</h1>

ChinookApp/WebApp/Pages/BasicDataMovement.cshtml
@page "{theInput?}"
@model WebApp.Pages.BasicDataMovementModel
@{
    ViewData["Title"] = "Basic Movement"; //title for your browser tag
}
<h1>Basic Data Movement</h1>

@if (!string.IsNullOrWhiteSpace(Model.MyName))
{
<p style="color: firebrick; font-weight: bold;">@Model.MyName</p>
}
else
{
    <p>The random number is odd.</p>
}

<form method="post">
    <label>
        Enter a number
        <input type="text" asp-for="theInput" />
    </label>
    <button type="submit" value="A" id="theButton" name="TheButton" asp-page-handler="AButton">A Button</button>
    &nbsp;&nbsp;
    <button type="submit" value="B" id="theButton" name="TheButton" asp-page-handler="BButton">B Button</button>
    <br /><br />
    <p style="color:green; font-weight:bold;">@Model.FeedBackMessage</p>
</form>

ChinookApp/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1 class="display-4">
<img src="~/img/ChinookMusic.jpg" alt="Chinook Music image" />
Welcome</h1>
<p>Version: @Model.DbVersion.Version Released: @Model.DbVersion.ReleaseDate</p>
<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

ChinookApp/WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    @* https://vvkor.github.io/d0
        <link href="https://cdn.jsdelivr.net/npm/d0css@1/dist/d0.min.cs" rel="stylesheet" />*@
    @* http://holidaycss.js.org *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a asp-area="" asp-page="/Index">
                        <img src="~/img/ChinookMusicMenuLogo.jpg" alt="Logo image" />
                    </a>
                </li>
                <li>
                    <a asp-area="" asp-page="/Index">Home</a>
                </li>
                @* setup a sub menu using holiday.css
                    see holidaycss.js.org *@
                <li>
                    <span>Samples</span>
                    <ul>
                        <li><a asp-area="" asp-page="/BasicDataMovement">Basics</a></li>
                        <li><a asp-area="" asp-page="/AlbumQuery">Album Query</a></li>
                    </ul>
                </li>
                <li>
                    <a asp-area="" asp-page="/Privacy">Privacy</a>
                </li>
                <partial name="_LoginPartial" />
            </ul>
        </nav>
        <!--
        d0css menu
        <nav>
        <ul class="navbar-nav flex-grow-1">
            <li>
                <a asp-area="" asp-page="/Index">Home</a>
            </li>-->
        @* setup a sub menu using d0css
            see vvkor.github.io/d0
            author is from St Petersburg Russia *@
        <!--<li>
                    <a href="#layout_sub">Samples</a>
                    <ul id="layout-sub">
                        <li><a asp-area="" asp-page="/BasicDataMovement">Basics</a></li>
                        <li><a asp-area="" asp-page="/ArtistQuery">Artist Query</a></li>
                    </ul>
                </li>
                <li>
                    <a asp-area="" asp-page="/Privacy">Privacy</a>
                </li>
                <partial name="_LoginPartial" />
            </ul>
        </nav>-->
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        &copy; 2021 - WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>